#!/bin/bash
# Installs the GitHub auto-sync post-commit hook.
# Run this after cloning or after a post-merge to keep the hook active.
set -e

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
HOOK_FILE="$HOOKS_DIR/post-commit"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SYNC_SCRIPT="$SCRIPT_DIR/github-sync-hook.sh"

chmod +x "$SYNC_SCRIPT"

cat > "$HOOK_FILE" <<EOF
#!/bin/bash
# Auto-generated by install-github-hook.sh — do not edit manually
exec "$SYNC_SCRIPT"
EOF

chmod +x "$HOOK_FILE"
echo "[github-sync] post-commit hook installed at $HOOK_FILE"
